version: '3.4'

services:
  db:
    restart: unless-stopped
    image: postgis/postgis:10-3.0
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: insecure!
      POSTGRES_DB: wa_pd_data
      PGDATA: /var/lib/postgresql/data/10.10
    networks:
      - wa_pd_dev
    volumes:
      - ../../data/dbdata:/var/lib/postgresql/data

  django:
    restart: unless-stopped
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8002:8000
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: db
    volumes:
      - .:/app
      - ../../data/agency_attachments:/app/data/agency_attachments
    depends_on:
      - db
    networks:
      - wa_pd_dev

networks:
  wa_pd_dev:
    driver: bridge
