# Generated by Django 3.1.2 on 2020-10-07 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agencies_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('awaiting-cleaning', 'Awaiting final cleaning'), ('awaiting-csv', 'Awaiting conversion to CSV'), ('awaiting-reading', 'Awaiting reading/processing'), ('awaiting-extraction', 'Awaiting extraction (email)'), ('non-request', 'Misc file/unrelated to response'), ('unchecked', 'New/Unprocessed')], default='unchecked', help_text='Status of processing the response document', max_length=30)),
                ('file', models.FileField(blank=True, help_text="The original file sent by the agency. This shouldn't need to be changed.", null=True, upload_to=documents.util.document_file_path)),
                ('current_file', models.FileField(blank=True, help_text='The current processed version of the file.', null=True, upload_to=documents.util.document_file_path)),
                ('notes', models.TextField(blank=True, help_text='Any notes about this document', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=documents.util.document_file_path)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('awaiting-cleaning', 'Awaiting final cleaning'), ('awaiting-csv', 'Awaiting conversion to CSV'), ('awaiting-reading', 'Awaiting reading/processing'), ('awaiting-extraction', 'Awaiting extraction (email)'), ('non-request', 'Misc file/unrelated to response'), ('unchecked', 'New/Unprocessed')], default='unchecked', help_text='Status of processing the response document', max_length=30)),
                ('source_page', models.CharField(blank=True, help_text='The source page(s) a CSV was created from in an original PDF', max_length=20, null=True)),
                ('source_sheet', models.CharField(blank=True, help_text='The source sheet a CSV was created from in an original XLS/X', max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_documents_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, help_text='The original document this processed version is extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_documents_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='processeddocument',
            constraint=models.UniqueConstraint(fields=('document', 'file'), name='unique-processed-agency-file'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('agency', 'file'), name='unique-agency-file'),
        ),
    ]
