# Generated by Django 3.1.2 on 2020-10-08 03:23

from django.db import migrations, models
import documents.util


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='current_file',
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='file',
            field=models.FileField(blank=True, help_text='The processed version of the original document', null=True, upload_to=documents.util.document_file_path),
        ),
    ]
