# Generated by Django 3.1.2 on 2020-10-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20201008_0323'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='processeddocument',
            index=models.Index(fields=['status'], name='documents_p_status_5a362a_idx'),
        ),
    ]
