# Generated by Django 3.1.2 on 2020-10-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20201010_2148'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='processeddocument',
            constraint=models.UniqueConstraint(fields=('file',), name='unique-processed-file'),
        ),
    ]
