# Generated by Django 3.1.2 on 2020-10-11 00:07

from django.db import migrations, models
import documents.util


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20201010_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text="The original file sent by the agency. This shouldn't need to be changed.", max_length=500, null=True, upload_to=documents.util.document_file_path),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='file',
            field=models.FileField(blank=True, help_text='The processed version of the original document', max_length=500, null=True, upload_to=documents.util.document_file_path),
        ),
    ]
