# Generated by Django 3.1.2 on 2020-10-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20201011_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Field Category',
                'verbose_name_plural': 'Field Categories',
                'ordering': ('fieldname', 'value'),
            },
        ),
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ('name',), 'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AddIndex(
            model_name='fieldcategory',
            index=models.Index(fields=['fieldname'], name='documents_f_fieldna_7e903d_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldcategory',
            index=models.Index(fields=['fieldname', 'value'], name='documents_f_fieldna_610cc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldcategory',
            constraint=models.UniqueConstraint(fields=('fieldname', 'value'), name='unique-field-value'),
        ),
    ]
