# Generated by Django 3.1.2 on 2020-10-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20201012_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcategory',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
