# Generated by Django 3.1.2 on 2020-10-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_fieldcategory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='related',
            field=models.ManyToManyField(help_text='This document is related to (or part of) another document/incident', related_name='_document_related_+', to='documents.Document'),
        ),
    ]
