# Generated by Django 3.1.2 on 2020-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='no_new_records',
            field=models.BooleanField(default=False, help_text='Check this if this document contains no new records. This shortcuts all processed document checking for completion status anb marks this document as complete (no parsing required)'),
        ),
    ]
