# Generated by Django 3.1.2 on 2020-10-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_no_new_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='population',
            field=models.IntegerField(blank=True, help_text='Population of the city this agency serves (for sorting)', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='related',
            field=models.ManyToManyField(blank=True, help_text='This document is related to (or part of) another document/incident', related_name='_document_related_+', to='documents.Document'),
        ),
    ]
