# Generated by Django 3.1.2 on 2020-10-17 01:17

from django.db import migrations, models


def add_population(apps, schema_editor):
    City = apps.get_model('cities', 'City')
    Agency = apps.get_model('documents', 'Agency')
    for agency in Agency.objects.all():
        if "county" in agency.name.lower():
            continue

        population = None
        city_name = agency.name.replace(
            "Police Department", ""
        ).replace(
            "Marshals Office", ""
        ).replace(
            "Sheriff's Office", ""
        ).strip()
        city = City.objects.filter(
            region__name="Washington", name=city_name
        ).first()
        if city:
            population = city.population

        # based on approx student counts
        if not city and city_name == "Eastern Washington University":
            population =  12633
        if not city and city_name == "Western Washington University":
            population = 16142
        if not city and city_name == "University of Washington":
            population = 47571
        # typo ... :/
        if not city and city_name  == "Central Washington University Washington":
            population = 12342
        # not in cities DB for some reason
        if not city and city_name == "Sedro-Wooley":
            population = 10540
        # county
        if city_name == "King County":
            population = 2252782

        if population is None:
            print("No city found for: %s" % (city_name))
            continue

        print("City name", city_name, "Population", population)
        agency.population = population
        agency.save()


def back_population(apps, schema_editor):
    Agency = apps.get_model('documents', 'Agency')
    for agency in Agency.objects.all():
        agency.population = None
        agency.save() # triggers population save


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_population_field'),
    ]

    operations = [
        migrations.RunPython(add_population, back_population)
    ]
