# Generated by Django 3.1.2 on 2021-05-23 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0015_auto_20210523_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='syntheticdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syntheticdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntheticdocuments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syntheticdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='syntheticdocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='syntheticdocuments_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syntheticdocument',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='The original document(s) this file was based on', to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='syntheticdocument',
            name='processed_documents',
            field=models.ManyToManyField(blank=True, help_text='The processed document(s) this file was based on', to='documents.ProcessedDocument'),
        ),
    ]
