# Generated by Django 3.1.2 on 2021-05-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_syntheticdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('supporting-document', 'Supporting document (complete)'), ('awaiting-cleaning', 'Awaiting final cleaning'), ('awaiting-csv', 'Awaiting conversion to CSV'), ('awaiting-reading', 'Awaiting reading/processing'), ('awaiting-extraction', 'Awaiting extraction'), ('non-request', 'Misc file/unrelated to response'), ('exemption-log', 'Exemption log'), ('unchecked', 'New/Unprocessed')], default='unchecked', help_text='Status of processing the response document', max_length=30),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('supporting-document', 'Supporting document (complete)'), ('awaiting-cleaning', 'Awaiting final cleaning'), ('awaiting-csv', 'Awaiting conversion to CSV'), ('awaiting-reading', 'Awaiting reading/processing'), ('awaiting-extraction', 'Awaiting extraction'), ('non-request', 'Misc file/unrelated to response'), ('exemption-log', 'Exemption log'), ('unchecked', 'New/Unprocessed')], default='unchecked', help_text='Status of processing the response document', max_length=30),
        ),
    ]
