# Generated by Django 3.1.2 on 2021-07-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_auto_20210525_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='request_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agency',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('awaiting-cleaning', 'Awaiting final cleaning'), ('awaiting-csv', 'Awaiting conversion to CSV'), ('awaiting-reading', 'Awaiting reading/processing'), ('awaiting-extraction', 'Awaiting extraction'), ('non-request', 'Misc file/unrelated to response'), ('supporting-document', 'Supporting document (complete)'), ('exemption-log', 'Exemption log'), ('unchecked', 'New/Unprocessed')], default='unchecked', help_text='Status of processing the response document', max_length=30),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('awaiting-cleaning', 'Awaiting final cleaning'), ('awaiting-csv', 'Awaiting conversion to CSV'), ('awaiting-reading', 'Awaiting reading/processing'), ('awaiting-extraction', 'Awaiting extraction'), ('non-request', 'Misc file/unrelated to response'), ('supporting-document', 'Supporting document (complete)'), ('exemption-log', 'Exemption log'), ('unchecked', 'New/Unprocessed')], default='unchecked', help_text='Status of processing the response document', max_length=30),
        ),
    ]
