# Generated by Django 3.1.2 on 2021-08-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20210729_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('awaiting-cleaning', 'Awaiting final cleaning'), ('awaiting-csv', 'Awaiting conversion to CSV'), ('awaiting-reading', 'Awaiting reading/processing'), ('awaiting-extraction', 'Awaiting extraction'), ('non-request', 'Misc file/unrelated to response'), ('supporting-document', 'Supporting document (complete)'), ('case-doc', 'Document related to an incident (to be linked/parsed)'), ('extractor', 'Code/script used for processing document'), ('exemption-log', 'Exemption log'), ('unchecked', 'New/Unprocessed')], default='unchecked', help_text='Status of processing the response document', max_length=30),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('awaiting-cleaning', 'Awaiting final cleaning'), ('awaiting-csv', 'Awaiting conversion to CSV'), ('awaiting-reading', 'Awaiting reading/processing'), ('awaiting-extraction', 'Awaiting extraction'), ('non-request', 'Misc file/unrelated to response'), ('supporting-document', 'Supporting document (complete)'), ('case-doc', 'Document related to an incident (to be linked/parsed)'), ('extractor', 'Code/script used for processing document'), ('exemption-log', 'Exemption log'), ('unchecked', 'New/Unprocessed')], default='unchecked', help_text='Status of processing the response document', max_length=30),
        ),
    ]
