# Generated by Django 3.1.2 on 2021-09-18 01:08

from django.db import migrations


def fix_lacey_pd(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ProcessedDocument = apps.get_model('documents', 'ProcessedDocument')
    ProcessedDocument.objects.filter(
        file__endswith="Lacey Police Department/Use_of_Force_2019_Added_Fields.docx"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20210802_1931'),
    ]

    operations = [
        migrations.RunPython(fix_lacey_pd)
    ]
