# Generated by Django 3.1.2 on 2022-01-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_auto_20220127_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddocument',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
