# Generated by Django 3.1.2 on 2022-01-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_processeddocument_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddocument',
            name='pages',
            field=models.IntegerField(blank=True, help_text='Pages in this document, if applicable', null=True),
        ),
    ]
