# Generated by Django 3.1.2 on 2022-03-26 00:31

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_auto_20220129_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='notes',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='notes_html'),
        ),
        migrations.AddField(
            model_name='agency',
            name='notes_html',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
    ]
