# Generated by Django 3.1.2 on 2022-03-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_auto_20220326_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='have_full_incident_documents',
            field=models.BooleanField(blank=True, help_text='Whether or not we have full incident document files as opposed to a summary or just a spreadsheet of incidents.', null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='have_incident_summaries',
            field=models.BooleanField(blank=True, help_text='Whether or not we have summary information about incidents', null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='have_officer_names',
            field=models.CharField(blank=True, choices=[('full', 'Full names'), ('last', 'Last only'), ('none', 'No names')], help_text='Whether or not we have officer names', max_length=30, null=True),
        ),
    ]
