# Generated by Django 3.1.2 on 2022-03-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_auto_20220328_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='have_complaints',
            field=models.BooleanField(blank=True, help_text='Select this if we have complaint data.', null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='have_structured_data',
            field=models.BooleanField(blank=True, help_text='Select this if we received structured data from the agency (Excel, etc).', null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='have_uof',
            field=models.BooleanField(blank=True, help_text='Select this if we have UOF data.', null=True),
        ),
    ]
